apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'    
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internal
    
  name: istio-frb-alb
  namespace: istio-system
spec:
  rules:
  - http:
      paths:
        - path: /*
          pathType: Prefix
          backend:
            service:
              name: productpage
              port:
                  number: 9080
